channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
  - git
  - pip:
    - numdiftools>=0.9.2
    - git+https://github.com/OpenHydrology/lmoments3.git
    - git+https://github.com/kikocorreoso/scikit-extremes.git
