channels:
  - conda-forge
dependencies:
  - python>=3
  - sphinx>=1.6
  - numpy
  - scipy
  - numdiftools>=0.9.2
  - matplotlib
  - git
  - pip:
    - git+https://github.com/OpenHydrology/lmoments3.git
    - git+https://github.com/kikocorreoso/scikit-extremes.git
